$(document).ready(function(){
   $("#nameErr").hide();
   $("#genderErr").hide();
   $("#emailErr").hide();
   $("#schoolErr").hide();
   $("#accountErr").hide();
   $("#password1Err").hide();
   $("#password2Err").hide();
   $("#passwordErr").hide();
   });
